ecommerceproject/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ecommerceproject/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('/cart/', include('cart.urls')),
    path('/user/', include('user.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.AllprodCat, name='AllprodCat'),
    path('<slug:c_slug>/', views.AllprodCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdDetail, name='products_category_detail'),

]

ecommerceproject/user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product, Category


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def subtotal(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6b4158b1c1.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}
    This is the cart page. proceed to review and place your order
{% endblock %}
{% block title %}
    Cart - ABC Company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'shop:AllprodCat' %}">Here</a> to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left-rounded custom_image" ></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: ₹ {{cart_item.product.price}}
                    <br>
                    Qty: {{cart_item.quantity}} x ₹ {{cart_item}}
                </td>
                <td>
                    ₹ {{cart_item.subtotal}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-plus custom_icon"></i></a>
                    &nbsp; <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus custom_icon"></i></a>
                    &nbsp; <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa-solid fa-trash custom_icon"></i></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp; <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus custom_icon"></i></a>
                    &nbsp; <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa-solid fa-trash custom_icon"></i></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
             <thead class="my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        PLease Review your shopping cart items before proceeding to payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total is : <strong>{{total}}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx_auto">
            <a href="{% url 'shop:AllprodCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    {% if category %}
        {{category.name}} - ABC store
    {% else %}
        See our new collections - ABC store
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p><a href="{% url 'shop:AllprodCat' %}">Our Product Collections</a></p>
                </div>
            </div>
    {% endif %}
        </div>
        <div class="container">
            {% if category %}
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="500px" height="300px">
            </div>
                <br>
            <div>
                <h1 class="text-center my_title">{{category.name}}</h1>
                <p class="text-justify">{{category.description}}</p>
            </div>
            {% else %}
            <div>
                <img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" alt="our products" width="100%" height="300px">
            </div>
                <br>
            <div>
                <h1 class="text-center my_title">Our Product Collections</h1>
                <p class="text-justify">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>
            </div>
            {% endif %}
<div class="container">
    <div class="row">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>₹ {{product.price}}</p>
        </div>
        </div>
    </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
    </div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; SARATH tech pvt ltd. All Rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:AllprodCat' %}"><img src="{% static 'img/logo.png' %}" alt="logo_image" height="80px" width="180px"></a>
  </center>
</header>

ecommerceproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}
{% load static %}

ecommerceproject/templates/login.html
{% extends 'home.html' %}
{% block content %}

<section class="vh-100">
  <div class=" container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class=" col col-xl-10" style="">
        <div class="card" style="box-shadow: 0 8px 20px 0px #1f1f1f1a;border-radius: 10px;">
          <div class="row g-0">
            <div class="col-sm-2"></div>
              <div class="col-sm-8 align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">

                  <form  method="post" >
                    {% csrf_token %}
                    <div class=" align-items-center mb-3 pb-1">
                      <h class="heading-name h1 fw-bold mb-0 ">Sign</h>
                    </div>

                    <h5 class="fw-normal mb-3 pb-3 text-muted" style="letter-spacing: 1px;">Sign into your account</h5>

                    <div class="form-outline mb-4">
                      <input type="text" id="form2Example17" class="form-control form-control-lg" name="username" placeholder="Username" />
                    </div>

                    <div class="form-outline mb-4">
                      <input type="password" id="form2Example27" class="form-control form-control-lg" name="password" placeholder="Password"/>
                    </div>

                    <div class="pt-1 mb-4">
                      <button class="col-sm-12 btn btn-dark btn-lg btn-block" type="submit">Login</button>
                    </div>

                    <p class="small text-center" style="color: #393f81;">Don't have an account?
                      <a href="{% url 'user:register' %}" style="color: #393f81;text-decoration:none">Register here</a>
                    </p>
                    {% for msg1 in messages %}
                    <div class="alert alert-primary" role="alert">
                      {{msg1}}
                    </div>
                    {% endfor %}

                  </form>
                </div>
              </div>
            <div class="col-sm-2 col-lg-7 d-flex align-items-center"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:AllprodCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}" >
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:AllprodCat' %}">All Products</a></li>
            {% for link in links %}
            <li><a class="dropdown-item" href="{{link.get_url}}">{{link.name}}</a></li>
            {% endfor %}
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping">({{item_count}})</i></a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" style="color:blue;">{{user.username}}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}">Log out</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}">Sign In</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'user:register' %}">Register</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}
  {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
  {% if category %}
    {{product.name}} - ABC store
  {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
  <div class="mx_auto">
    <p><a href="{% url 'shop:AllprodCat' %}">Home</a>|<a href="{{product.category.url}}">{{product.category}}</a>|{{Product.name}}</p>
  </div>
</div>
<div class="container">
<br>
<div class="row">
  <div class="col-6 col-sm-6 col-md-6 col-lg-6">
      <img src="{{product.image.url}}" alt="{{product.name}}" style="min-width :10rem" width="500px" height="300px">
  </div>

  <div class="col-6 col-sm-6 col-md-6 col-lg-6">
      <h1 class="my_prod_title">{{product.name}}</h1>
      <p>₹{{product.price}}</p>
      <p class="my_title">Product Description</p>
      <p class="text-justify my_prod_text">{{product.description}}</p>
      {% if product.stock <= 0 %}
      <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
      {% else %}
      <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-secondary">Add to Cart</a>
      {% endif %}
  </div>

</div>
</div>
{% endblock %}

ecommerceproject/templates/register.html
{% extends 'home.html' %}
{% block content %}

<div class="wrapper">
        <div class="form-left">
            <h2 class="text-uppercase">Login</h2>
            <p>
                We are here to help you
            </p>
            <p class="text">
                <span>If you are already registered , Please Sign IN</span>
            </p>
            <div class="form-field">
                <a href="{% url 'user:login' %}"><input type="submit" class="account" value="Have an Account?"></a>
            </div>
            {% for msg1 in messages %}
            <div class="alert alert-primary" role="alert">
                {{msg1}}
            </div>
             {% endfor %}


        </div>

        <form method="post" class="form-right">
            {% csrf_token %}
            <h2 class="text-uppercase">Registration form</h2>
            <div class="mb-3">
                <label>Username</label>
                <input type="text" class="input-field" name="username" required>
            </div>
            <div class="row">
                <div class="col-sm-6 mb-3">
                    <label>Password</label>
                    <input type="password" name="password" id="pwd" class="input-field">
                </div>
                <div class="col-sm-6 mb-3">
                    <label>Confirm Password</label>
                    <input type="password" name="password1" id="cpwd" class="input-field">
                </div>
            </div>
            <div class="mb-3">
                <label class="option">I agree to the <a href="#">Terms and Conditions</a>
                    <input type="checkbox" checked>
                    <span class="checkmark"></span>
                </label>
            </div>
            <div class="form-field">
                <button type="submit" class="register">Submit</button>
            </div>
        </form>
    </div>

{% endblock %}